[package]
name = "pxtone"
version = "0.1.0"
authors = ["petamoriken <moriken@kimamass.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
byteorder = "1.3.1"
num-traits = "0.2.6"
num-derive = "0.2.4"
failure = "0.1.5"
